### ISSUE TITLE
Cloning issue

### ISSUE THREAD

**Issue by Praneeth0984** [hristianivanov/School-WebProject#14]
I tried cloning the project and running it it is giving me a issue like The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[22496] DevHunter.Web.exe' has exited with code 2147516566 (0x80008096). can u please guide me on how to resolve this issue

**Comment by hristianivanov** [comment]
Change the server name in connection string located in DevHunter.Web/appsettings.json
